apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferenceGrant
metadata:
  name: spring-boot
  namespace: spring-boot-sbc
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Service
      namespace: spring-boot-sba
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: spring-boot-sba
  to:
    - group: ""
      kind: Service
      name: spring-boot-admin-client