---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: consul
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: consul
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: consul
spec:
  replicas: $BACKEND_REPLICAS
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      namespace: consul
      labels:
        app: backend
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
        'consul.hashicorp.com/enable-metrics-merging': 'true'
        'consul.hashicorp.com/transparent-proxy-overwrite-probes': 'true'
        'k8s.v1.cni.cncf.io/networks': '[{ "name":"consul-cni" }]'
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: nicholasjackson/fake-service:v0.26.2
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 500Mi
          env:
            - name: "NAME"
              value: "backend-service"
            - name: MESSAGE
              value: "$SVC_CLUSTER:BACKEND $SVC_CLUSTER:BACKEND $SVC_CLUSTER:BACKEND $SVC_CLUSTER:BACKEND"
            - name: LOG_LEVEL
              value: trace
            - name: LISTEN_ADDR
              value: 0.0.0.0:9191
            - name: SERVER_TYPE
              value: "http"
            - name: UPSTREAM_URIS
              value: "$UPSTREAM_URIS"
          ports:
            - containerPort: 9191
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: 9191
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 9191
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 2
          startupProbe:
            httpGet:
              path: /ready
              port: 9191
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 2