apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
  namespace: consul
spec:
  protocol: http
  transparentProxy:
    dialedDirectly: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: backend
  namespace: consul
spec:
  protocol: http
  transparentProxy:
    dialedDirectly: true
---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ServiceDefaults
#metadata:
#  name: google
#  namespace: default
#spec:
#  protocol: tcp
#  transparentProxy:
#    dialedDirectly: true
#  destination:
#    port: 443
#    addresses:
#      - example.com
#---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ServiceDefaults
#metadata:
#  name: webpage
#  namespace: default
#spec:
#  protocol: tcp
#  transparentProxy:
#    dialedDirectly: true
#  destination:
#    port: 443
#    addresses:
#      - jsonplaceholder.typicode.com
#---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ServiceDefaults
#metadata:
#  name: httpbin
#  namespace: default
#spec:
#  protocol: tcp
#  transparentProxy:
#    dialedDirectly: true
#  destination:
#    port: 443
#    addresses:
#      - httpbin.org
#---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ServiceDefaults
#metadata:
#  name: apk-package-repo
#  namespace: default
#spec:
#  protocol: tcp
#  transparentProxy:
#    dialedDirectly: true
#  destination:
#    port: 443
#    addresses:
#      - dl-cdn.alpinelinux.org
---
#apiVersion: consul.hashicorp.com/v1alpha1
#kind: ServiceDefaults
#metadata:
#  name: counting
#  namespace: default
#spec:
#  protocol: tcp
#  transparentProxy:
#    dialedDirectly: true
#  destination:
#    port: 9001
#    addresses:
#      - counting-1.default.svc.cluster.local
#      - counting-2.default.svc.cluster.local
#      - counting-3.default.svc.cluster.local
#      - counting-4.default.svc.cluster.local
#      - counting-5.default.svc.cluster.local
#      - counting-6.default.svc.cluster.local
#      - counting-7.default.svc.cluster.local
#      - counting-8.default.svc.cluster.local
#      - counting-9.default.svc.cluster.local
#      - counting-10.default.svc.cluster.local