apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: backend
  namespace: consul
spec:
  connectTimeout: 5s
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: frontend
  namespace: consul
spec:
  connectTimeout: 5s
#  loadBalancer:
#    policy: least_request
#    leastRequestConfig:
#      choiceCount: 2
